wip

diff --git a/watchpuppy b/watchpuppy
--- a/watchpuppy
+++ b/watchpuppy
@@ -10,47 +10,46 @@ LOG_LEVEL=${LOG_LEVEL:-INFO}
 
 # Log according to LOG_LEVEL
 log() {
-    local LEVEL=$1
-    local MESSAGE=$2
+    local level=$1
+    local message=$2
 
     # Log level precedence mapping
-    declare -A LEVELS=( ["DEBUG"]=10 ["INFO"]=20 ["WARNING"]=30 ["ERROR"]=40 ["CRITICAL"]=50 )
+    declare -A levels=( ["DEBUG"]=10 ["INFO"]=20 ["WARNING"]=30 ["ERROR"]=40 ["CRITICAL"]=50 )
 
-    if [ "${LEVELS[$LEVEL]}" -ge "${LEVELS[$LOG_LEVEL]}" ]; then
-        echo "$SCRIPT_NAME - $LEVEL - $MESSAGE"
+    if [ "${levels[$level]}" -ge "${levels[$LOG_LEVEL]}" ]; then
+        echo "$SCRIPT_NAME - $level - $message"
     fi
 }
 
 monitor() {
-    local LEVEL=$1
-    local MESSAGE=$2
     log "INFO" "Starting file watcher on directory: $WATCH_DIR"
     log "INFO" "Process script: $PROCESS_SCRIPT"
 
     # Monitor the directory for new files and react to close_write events
-    inotifywait -m -r -e close_write --format '%w%f' "$WATCH_DIR" | while read -r NEWFILE
+    inotifywait -m -r -e close_write --format '%w%f' "$WATCH_DIR" | while read -r new_file
     do
-        log "INFO" "New file detected: $NEWFILE"
+        log "INFO" "New file detected: $new_file"
 
         # Run the process script
-        if ! "$PROCESS_SCRIPT" "$NEWFILE"; then
-            log "ERROR" "Error executing $PROCESS_SCRIPT with $NEWFILE"
+        if ! "$PROCESS_SCRIPT" "$new_file"; then
+            log "ERROR" "Error executing $PROCESS_SCRIPT with $new_file"
         else
-            log "INFO" "Successfully processed $NEWFILE with $PROCESS_SCRIPT"
+            log "INFO" "Successfully processed $new_file with $PROCESS_SCRIPT"
         fi
     done
 }
 
 # Check if the filesystem type supports inotify
 check_inotify_support() {
-  localh fs_type=$(stat -f -c %T "$WATCH_DIR")
+  local fs_type=
+  fs_type="$(stat -f -c %T "$WATCH_DIR")"
 
   # These file systems do not support inotify
-  if [[ "$FS_TYPE" == "v9fs" || "$FS_TYPE" == "fuseblk" || "$FS_TYPE" == "nfs" || "$FS_TYPE" == "cifs" || "$FS_TYPE" == "smbfs" || "$FS_TYPE" == "overlayfs" ]]; then
-      log "DEBUG" "File system $FS_TYPE does not support inotify. Switching to Python polling."
+  if [[ "$fs_type" == "v9fs" || "$fs_type" == "fuseblk" || "$fs_type" == "nfs" || "$fs_type" == "cifs" || "$fs_type" == "smbfs" || "$fs_type" == "overlayfs" ]]; then
+      log "DEBUG" "File system $fs_type does not support inotify. Switching to Python polling."
       return 1
   else
-      log "DEBUG" "File system $FS_TYPE supports inotify. Using inotifywait."
+      log "DEBUG" "File system $fs_type supports inotify. Using inotifywait."
       return
   fi
 }
@@ -68,5 +67,5 @@ if check_inotify_support; then
     monitor
 else
     # with exec the python process replaces the shell process as main process.
-    exec python3 /path/to/watchpuppy.py "$WATCH_DIR" "$PROCESS_SCRIPT"
+    exec python3 "$SCRIPT_DIR/watchpuppy.py" "$WATCH_DIR" "$PROCESS_SCRIPT"
 fi
